    - name: Inject version into code
      run: |
        echo "#pragma once" > version.h
        echo "#define FW_VERSION \"${{ steps.bump.outputs.new }}\"" >> version.h

    - name: Compile firmware
      run: |
        arduino-cli compile --fqbn esp32:esp32:esp32doit-devkit-v1 . --output-dir build

    - name: Copy firmware to folder
      run: |
        mkdir -p firmware
        cp build/*.bin firmware/firmware.bin

    - name: Commit updated version and firmware
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add firmware/version.txt version.h firmware/firmware.bin
        git commit -m "Auto-version: ${{ steps.bump.outputs.new }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
